name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  API_TOKEN: ${{ secrets.API_TOKEN }} 
  API_URL: ${{ secrets.API_URL }} 
  APP_DOMAIN: ${{ secrets.APP_DOMAIN }} 

jobs:

  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Echo secrets
      run: |
        echo API_URL ${{env.API_URL}}
        echo APP_DOMAIN ${{env.APP_DOMAIN}}
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/onestromberg/strapi_educatio:latest
        docker push ghcr.io/onestromberg/strapi_educatio:latest
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY_GITACTIONS }}
        script: |
            bash ~/bootstrap.sh nextjs
  deploy:
    runs-on: ubuntu-latest
    needs: [build-publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_GITACTIONS }}
          script: |
              bash ~/bootstrap.sh strapi
